# ==================================================================================================
# Configuración Principal del Sitio - VERSIÓN FINAL
# ==================================================================================================
site:
  name: 'Apex Data Labs'
  site: 'https://www.apex-data.io'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: ''

# ==================================================================================================
# Metadatos por Defecto para SEO - SECCIÓN CORREGIDA
# ==================================================================================================
metadata:
  title:
    default: 'Apex Data Labs | Data Strategy & Engineering Portfolio'
    template: '%s — Apex Data Labs'
  description: "A professional portfolio showcasing projects and articles on data platforms, AI strategy, and analytics."
  
  robots:
    index: true
    follow: true
  
  openGraph:
    site_name: 'Apex Data Labs'
    images:
      - url: '~/assets/images/social.png'
        width: 1200
        height: 628
    type: website
  
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

# ==================================================================================================
# Idioma
# ==================================================================================================
i18n:
  language: en
  textDirection: ltr

# ==================================================================================================
# Configuración de la sección de Artículos
# ==================================================================================================
apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: 'articles/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'articles'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

# ==================================================================================================
# Analítica y UI
# ==================================================================================================
analytics:
  vendors:
    googleAnalytics:
      id: 'G-JSPFG923QG'
ui:
  theme: 'system'

# ==================================================================================================
# Configuración de Markdown - SECCIÓN AÑADIDA
# ==================================================================================================
markdown:
  remarkPlugins:
    - remark-math
  rehypePlugins:
    - rehype-katex